// This file is generated by icon spritesheet generator

export const iconNames = [
  'black-bishop',
  'black-king',
  'black-knight',
  'black-pawn',
  'black-queen',
  'black-rook',
  'white-bishop',
  'white-king',
  'white-knight',
  'white-pawn',
  'white-queen',
  'white-rook',
] as const

export type IconName = (typeof iconNames)[number]
